"""initial

Revision ID: 0f7e1267e3bd
Revises: 
Create Date: 2025-03-06 21:18:49.752151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f7e1267e3bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('functions_dict',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_functions_dict_id'), 'functions_dict', ['id'], unique=False)
    op.create_table('modules',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_id'), 'modules', ['id'], unique=False)
    op.create_table('property_code_dict',
    sa.Column('group_code', sa.String(length=30), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_code_dict_id'), 'property_code_dict', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('roles_dict',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_dict_id'), 'roles_dict', ['id'], unique=False)
    op.create_table('settings_dict',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_dict_id'), 'settings_dict', ['id'], unique=False)
    op.create_table('shablon_dict',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shablon_dict_id'), 'shablon_dict', ['id'], unique=False)
    op.create_table('status_dict',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_dict_id'), 'status_dict', ['id'], unique=False)
    op.create_table('timezone_dict',
    sa.Column('timezone_name', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timezone_dict_id'), 'timezone_dict', ['id'], unique=False)
    op.create_table('companies',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('inn', sa.String(length=16), nullable=False),
    sa.Column('kpp', sa.String(length=9), nullable=False),
    sa.Column('ogrn', sa.String(length=13), nullable=True),
    sa.Column('bic', sa.String(length=9), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property_code_dict.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inn'),
    sa.UniqueConstraint('kpp')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('role_functions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('function_code_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['function_code_id'], ['functions_dict.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles_dict.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_functions_id'), 'role_functions', ['id'], unique=False)
    op.create_table('settings',
    sa.Column('setting_code_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('active_from', sa.Date(), nullable=False),
    sa.Column('active_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['setting_code_id'], ['settings_dict.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_table('company_properties',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('property_code_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['property_code_id'], ['property_code_dict.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_properties_id'), 'company_properties', ['id'], unique=False)
    op.create_table('departments',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('license',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('license_key', sa.String(length=1000), nullable=False),
    sa.Column('active_from', sa.Date(), nullable=False),
    sa.Column('active_to', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_license_id'), 'license', ['id'], unique=False)
    op.create_table('module_company_links',
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('active_from', sa.Date(), nullable=False),
    sa.Column('active_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_company_links_id'), 'module_company_links', ['id'], unique=False)
    op.create_table('user_groups',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_groups_id'), 'user_groups', ['id'], unique=False)
    op.create_table('users',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('timezone_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('firstname', sa.String(length=60), nullable=False),
    sa.Column('lastname', sa.String(length=60), nullable=False),
    sa.Column('patronymic', sa.String(length=60), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('user_lock', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['user_groups.id'], ),
    sa.ForeignKeyConstraint(['timezone_id'], ['timezone_dict.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('user_properties',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('property_code_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_code_id'], ['property_code_dict.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_properties_id'), 'user_properties', ['id'], unique=False)
    op.create_table('user_report_links',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('active_from', sa.Date(), nullable=False),
    sa.Column('active_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_report_links_id'), 'user_report_links', ['id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('active_from', sa.Date(), nullable=False),
    sa.Column('active_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles_dict.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_table('user_sendings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('message', sa.String(length=4000), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['status_dict.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sendings_id'), 'user_sendings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sendings_id'), table_name='user_sendings')
    op.drop_table('user_sendings')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_user_report_links_id'), table_name='user_report_links')
    op.drop_table('user_report_links')
    op.drop_index(op.f('ix_user_properties_id'), table_name='user_properties')
    op.drop_table('user_properties')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_groups_id'), table_name='user_groups')
    op.drop_table('user_groups')
    op.drop_index(op.f('ix_module_company_links_id'), table_name='module_company_links')
    op.drop_table('module_company_links')
    op.drop_index(op.f('ix_license_id'), table_name='license')
    op.drop_table('license')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_company_properties_id'), table_name='company_properties')
    op.drop_table('company_properties')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_role_functions_id'), table_name='role_functions')
    op.drop_table('role_functions')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_timezone_dict_id'), table_name='timezone_dict')
    op.drop_table('timezone_dict')
    op.drop_index(op.f('ix_status_dict_id'), table_name='status_dict')
    op.drop_table('status_dict')
    op.drop_index(op.f('ix_shablon_dict_id'), table_name='shablon_dict')
    op.drop_table('shablon_dict')
    op.drop_index(op.f('ix_settings_dict_id'), table_name='settings_dict')
    op.drop_table('settings_dict')
    op.drop_index(op.f('ix_roles_dict_id'), table_name='roles_dict')
    op.drop_table('roles_dict')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_property_code_dict_id'), table_name='property_code_dict')
    op.drop_table('property_code_dict')
    op.drop_index(op.f('ix_modules_id'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_functions_dict_id'), table_name='functions_dict')
    op.drop_table('functions_dict')
    # ### end Alembic commands ###
