"""comapny created

Revision ID: 70aec22f6b7a
Revises: 9ef641098987
Create Date: 2025-03-08 12:05:27.950080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70aec22f6b7a'
down_revision: Union[str, None] = '9ef641098987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'created_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'created_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
