"""company update field created

Revision ID: 9ef641098987
Revises: b7ac94302ec2
Create Date: 2025-03-08 12:03:23.970400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef641098987'
down_revision: Union[str, None] = 'b7ac94302ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'created_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'created_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
